const CommandType = {
  CHECK_IN: 'Q0',
  HEARTBEAT: 'H0',
  UNLOCK: 'L0',
  LOCK: 'L1',
  LOCATION: 'D0',
  LOCATION_TRACKING: 'D1',
  STATUS: 'S5',
  ACTIVATE_ALARM: 'S8',
  FIRMWARE_INFO: 'G0',
  ALARM: 'W0',
  UPGRADE_AVAILABLE: 'U0',
  UPGRADE_DATA_REQUEST: 'U1',
  UPGRADE_RESULTS_NOTIFICATION: 'U2',
  BLE_KEY: 'K0',
  SIM_ICCID: 'I0',
  BLUETOOTH_MAC: 'M0',
  POWER_OFF: 'S0',
  REBOOT: 'S1',
  RFID_UNLOCK: 'C0',
  RFID_MANAGEMENT: 'C1',
};

module.exports = CommandType;
